### ISSUE TITLE
crosshair size "custom value" shows too much precision

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2424]
![2023-02-07_001](https://user-images.githubusercontent.com/1316300/217223903-e71d4b05-dcf2-43fd-aadc-5cb142b6d611.png)

There is no need to display that many zeroes in there.

**Comment by VReaperV** [comment]
This has been fixed at some point.

**Comment by slipher** [comment]
It can still happen; the "Custom value" thing just shows cvars however they are spelled in the cvar system. If you do `set cg_crosshairSize 1.000000` then you will see that. But with the current menu, there is no reason to have a value spelled that way in the first place; it can only happen if set manually by the user. So I'll leave this closed as being too minor to bother with.
