### ISSUE TITLE
The burning overmind animation is broken under some circumstances

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#3224]
It looks like this:

https://users.unvanquished.net/~sweet/videos/overmind-neck-pain.mp4

To reproduce, set the graphics to "low" via the menu, `ignite` the overmind and an egg nearby.

**Comment by VReaperV** [comment]
To be more specific, this is caused by `cg_lowQualityModels on`, probably some error in the low-quality skeletons.

**Comment by illwieckz** [comment]
With the low quality skeleton, the `destroy` animation plays correctly in IQE browser though.

**Comment by illwieckz** [comment]
The low quality model displays properly the `destroy` animation on my end in Dæmon engine too.

**Comment by VReaperV** [comment]
I guess this was fixed by #3377.

**Comment by illwieckz** [comment]
With Dæmon and Unvanquished commits older than that I still don't get the bug, so maybe other things fixed it before. We rewrote some other float stuff since that issue was reported.

I've tested some commits from April, I seen no bug.
I've tested current master, no more bug.
But I've also tested v0.55.0 which is older than this issue, and I see no bug as well…
