### ISSUE TITLE
Curses console prevents useful error output

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#466]
### Issue

The curses console, which defaults to on, causes error messages on both client and server crashes to disappear. Only for some crashes (gamelogic?) a stored log is printed. The result is that users that have no knowledge of the `+nocurses` switch will not be provided with any useful output and therefor the error cannot be reported to the developers in full. "Add +nocurses" was the standard response to many troubleshooting requests in the past and resulted in a slowdown of the debug process.

### Solution

Disable default curses, allow enabling it with `+curses`. This (printing ascii lines to stdout by default) is the standard behaviour of any other *nix daemon and any other GUI/graphical client application, so it will help greatly with standard compliance and user expectations, too.

In addition to disabling default curses, the error printing capabilities of the curses console in case of a client/server crash could be improved further, though obviously not every error can be caught and there will always be situations where relevant log lines are lost.

**Comment by Kangz** [comment]
@Amanieu, is this something fixed in sys_rewrite? Otherwise what would it take to rewrite con_log?

**Comment by Amanieu** [comment]
I haven't done anything for this. I think it's just a matter of dumping the console log on exit if there was an error.

**Comment by Viech** [comment]
This is implemented but doesn't work for all crashes. (And how would it work for *all* engine crashes, anyway?) I still heavily prefer my solution of making the curses frontend optional, so the few users who have special setups using `screen` can still enjoy it while the majority of users will have standard-compliant, fail-safe (given line-based flush on error) error logging.

**Comment by Amanieu** [comment]
Which crashes does this not work for? I'm sure we can make this work for all crashes.

**Comment by Viech** [comment]
SIGSEGV in the thread that is supposed to dump the log.

**Comment by Viech** [comment]
Well, either we finally make our fancy console work flawlessly by adding to the amount of special-treatment code (reliable log dumping for all kinds of crashes, terminal detection, color schemes) or we just change the default interface to line based printing to stdout and behave like every other daemon I know. The important bit is that it happens now, I'm sick of telling people to add +nocurses to their startup line all the time and to lose output myself on hard-to-reproduce crashes just because I forgot about the mandatory +nocurses.

Only if you run your server manually in a screen session curses makes any sense. For systemd/init we have console detection in place just so we can disable it… This really hurts my sense of [KISS](http://en.wikipedia.org/wiki/KISS_principle).

**Comment by Amanieu** [comment]
Fixed by dd30643

**Comment by DolceTriade** [comment]
Technically, not fixed until nacl-cgame is merged into master.
