### ISSUE TITLE
Can't register to the forum

### ISSUE THREAD

**Issue by vitamins** [Unvanquished/Unvanquished#871]
I always get the message
FORM_INVALID
When i click on "contact the board administrator" i get the same thing.
I have tried it in firefox, and chromium, in windows and linux.
Next website problem:
When i try to register an account for the wiki i get a blank page.

**Comment by cu-kai** [comment]
@DolceTriade

**Comment by DolceTriade** [comment]
Sorry :( still debugging. This isn't a fun issue.

**Comment by DolceTriade** [comment]
Should be fixed now.

**Comment by vitamins** [comment]
Still the same problem for me as yesterday. Please reopen.
On the page where you enter the nickname i get:
"The submitted form was invalid. Try submitting again."
When i select a language the page reloads and goes back to the "I agree to these terms" - page again.

**Comment by Viech** [comment]
If an issue is not fixed you'll get the feedback to reopen it, the other way round it's not always the case. :stuck_out_tongue_winking_eye:

**Comment by DolceTriade** [comment]
Forgot to clear the cache. This time for real.

**Comment by vitamins** [comment]
I registered an account. But i can not login.
"Wrong username or password."
I sure it is correct, i wrote it down on paper. Please reopen.

**Comment by DolceTriade** [comment]
THIS TIME FOR SURE. I forgot to update the login path from my staging to the real install...

**Comment by vitamins** [comment]
Thank you!
