### ISSUE TITLE
Shoot and crash - (Shader ?)

### ISSUE THREAD

**Issue by Buom01** [Unvanquished/Unvanquished#937]
Hi,
When an human shot, the game crash (not always with a visible error)
With a fresh install on **manjaro linux from the unvanquished aur package** I get from the **console**: http://pastebin.com/e5G0HeMc
The **log** is: http://pastebin.com/PGqQpsfp

Line that need attention is:
"nv50_program_translate:369 - shader translation failed: -4 "
because it's doesn't show in the log

**Graphic card**: VGA compatible controller: `NVIDIA Corporation G94 [GeForce 9600 GT] (rev a1)`
**Drivers**:
-   GL_VENDOR: nouveau
-   GL_RENDERER: Gallium 0.4 on NV94
-   GL_VERSION: 3.0 Mesa 11.2.2

**Processor** (64bit): Intel(R) Core(TM)2 Duo CPU     E8500  @ 3.16GHz 
**2 Display**: VGA(where unvanquished is running) and HDMI
**Game** version: Unvanquished 0.50 Linux x86_64 May 15 2016
**System**: Manjaro Linux KDE (64) up to date

**Comment by DolceTriade** [comment]
Ahh, can you try to reproduce this error in our official packages? Our official packages integrate breakpad which will allow us to capture a backtrace of the crash (alternatively, if you know how to get a backtrace, that would also suffice). Up front, those shader translation errors seem ominous... Could you try compiling the game with GLEW-git instead of the Arch packaged glew?

**Comment by Viech** [comment]
We should probably ping @gimhael.

**Comment by Buom01** [comment]
Sorry to answer late.

> I have formatting my system after disk corruption: I'm now on manjaro XFCE, with the same issue (also with nouveau)

I do:
# Preparing
$yaourt -Rnuc unvanquished opusfile unvanquished-data
$yaourt -Rdd glew
$yaourt --needed --noconfirm -Sy glew-git
$git clone https://github.com/Unvanquished/Unvanquished & cd Unvanquished

## Verififycation of dependencies:
- zlib: "core/**zlib** 1.2.8-4"
- libgmp: "core/**gmp** 6.1.0-4"
- libnettle: "core/**nettle** 3.2-2","community/**nettle4** 2.7.1-4","multilib/**lib32-nettle** 3.2-1","multilib/**lib32-nettle4** 2.7.1-4","aur/**lib32-nettle4** 2.7.1-3","aur/**nettle4** 2.7.1-4"
- libcurl: "core/**curl** 7.49.1-1"
- SDL2: "extra/**sdl2** 2.0.4-2","extra/**sdl2_gfx** 1:1.0.1-1","extra/**sdl2_image** 2.0.1-1","extra/**sdl2_mixer** 2.0.1-1","extra/**sdl2_net** 1:2.0.1-1","extra/**sdl2_ttf** 2.0.14-1","extra/**smpeg2** 1:2.0.0-2","multilib/**lib32-sdl2** 2.0.4-2","multilib/**lib32-sdl2_image** 2.0.1-1"
- GLEW: "aur/**glew-git** 1.13.9ef6bfb-1"
- libpng: "extra/**libpng** 1.6.23-1","multilib/**lib32-libpng** 1.6.21-1"
- libjpeg ≥ 8: "extra/**libjpeg-turbo** 1.5.0-1","multilib/**lib32-libjpeg-turbo** 1.4.2-1","aur/**libjpeg9** 9b-2"
- libwebp ≥ 0.2.0: "extra/**libwebp** 0.5.0-1","multilib/**lib32-libwebp** 0.5.0-1","aur/**lib32-libwebp** 0.5.0-1"
- Freetype: "extra/**freetype2** 2.6.3-1"
- OpenAL: "extra/**openal** 1.17.2-2"
- libogg: "extra/**libogg** 1.3.2-1","multilib/**lib32-libogg** 1.3.2-1"
- libvorbis: "extra/libvorbis 1.3.5-1","multilib/**lib32-libvorbis** 1.3.5-1"
- libtheora: "extra/**libtheora** 1.1.1-3" *(without lib32)*
- libopus: "extra/**opus** 1.1.2-1"
- libopusfile: "community/**opusfile** 0.7-2"

### Install compilation and optional
> mingw-w64-aria2 doesn't found

$yaourt -S --needed --noconfirm cmake python python-yaml python-jinja ncurses geoip mingw-w64-libgeoip mingw-w64-{toolchain,cmake}

# Compiling
$mkdir build && cd build
$cmake ..
$make
$../download-pk3.sh pkg

# Running
$./daemon
And ..... random result (generaly crash when a bot shot, and sometime freeze or simply exit with error), the last time, when connection on a server with the map chasm, the game seem to freeze entire computer, I try to press CTRL+ALT+F2 . After many second, it's appear with errors from my drivers:
https://www.dropbox.com/s/b2zqiwkgv900e0f/IMG_20160714_191053.jpg?dl=0

> The log doesn't show any usefull information, and because each time I have to reboot my computer, I haven't the console output

The question is now, is it really a Unvanquished issue ?

PS: I don't know how to get a backtrace

I also will try with nvidia drivers, but I remember that it's didn't work, but I remember that the game works with old version of unvanquished and manjaro

**Comment by Buom01** [comment]
# Running (after recompiling) with proprietary nvidia drivers
drivers: video-nvidia-304xx
## Running
An alert show: "Built-in shaders failed: Shaders failed to link!"

Important passage in the log (probably):
```bash
Warn: SSAO not used because GL_ARB_texture_gather is not available. 
Warn: Link log:
Fragment info
-------------
0(112) : error C7011: implicit cast from "int" to "uint"
 
Warn: Built-in shaders failed: Shaders failed to link! 
```

complete log: http://pastebin.com/T4jhYfQB

How to capture a backtrace with the breakpad ?

**Comment by Viech** [comment]
@DolceTriade ↑

**Comment by DolceTriade** [comment]
Note that the above issue is different than the issue in this thread. This reporter has issue even starting the game because his shaders don't compile, so a backtrace wouldn't be useful in this case. 

For the other people:
Download the official release here:
https://github.com/Unvanquished/Unvanquished/releases/download/v0.50.0/unvanquished_0.50.0.zip

Extract the .zip. There is a daemon binary inside. Run it. Reproduce the crash. When the game crashes, there will be a bunch of files in ~/.unvanquished/crashdump/. Upload those somewhere and give us the link so we can extract the backtrace.

**Comment by Buom01** [comment]
I have new informations with the official release; I get this:
http://pastebin.com/eYSQkg8N

"Warn: Built-in shaders failed: Couldn't compile vertex shader: deformVertexes"

**Comment by Viech** [comment]
@gimhael says this is fixed in 1095f17. You could try to compile the client binary from this commit instead. (No guarantee that it's compatible with the release though.)

**Comment by Incognito4nonymous** [comment]
`I have new informations with the official release; I get this:
http://pastebin.com/eYSQkg8N

"Warn: Built-in shaders failed: Couldn't compile vertex shader: deformVertexes"`
Desu! This is my issue, you got it fixed dude ? Glad the see I ain't the only one facing it.

**Comment by Incognito4nonymous** [comment]
> @gimhael says this is fixed in 1095f17. You could try to compile the client binary from this commit instead. (No guarantee that it's compatible with the release though.)
My version was downloaded September, and I'm still facing that issue. By the way the topic doesn't longer fit the issue as far as I'm aware.

**Comment by Buom01** [comment]
I have retried the game today (from AUR), it's work but I don't know the reason. I have a new CPU, a new motherboard, an other OS (antergos), but I kept my graphic card

**Comment by Viech** [comment]
I'll just close this for now, feel free to request a reopen when it reoccurs.
